### ISSUE TITLE
URL Encode the Issuer

### ISSUE THREAD

**Issue by Kevin-Andrew** [petrsnd/OtpCore#16]
Looks like you forgot this PR comment:
https://github.com/petrsnd/OtpCore/pull/10#pullrequestreview-1244459485

If I do the following code, when I input the `issuer` as "ACME & Co", I would expect to be able to parse the resulting URI string using standard libraries and be able to extract the same string, "ACME & Co". However, all I get is "ACME ".
```
var secret = new byte[] { 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07 };
var account = "myAccount";
var issuer = "ACME & Co";

var otp = new OtpAuthUri(OtpType.Totp, secret, account, issuer);

Console.WriteLine(otp.ToString());

var uri = new Uri(otp.ToString());

Console.WriteLine(uri.Query);

var query = System.Web.HttpUtility.ParseQueryString(uri.Query);

Console.WriteLine("'" + query["issuer"] + "'");
```

![image](https://user-images.githubusercontent.com/22459191/213224404-8b7b8f42-91c9-490b-94d0-9b30b3fbd0d9.png)

**Comment by petrsnd** [comment]
Dang. I focused so much on the uri string constructor and getting that right based on your feedback that I forgot to put this original use case in as a unit test to make sure it passed. The escaping is still missing for some of the individual parameters. I'll add the test and the code.
